
import { BookState } from '../types';
import JSZip from 'jszip';

export const generateKDPPackage = async (bookState: BookState) => {
    const zip = new JSZip();

    // 1. Create Manuscript File (e.g., in simple text format)
    let manuscriptContent = `Title: ${bookState.title || 'Untitled Book'}\n\n`;
    if (bookState.chapters) {
        bookState.chapters.forEach((chapter, index) => {
            manuscriptContent += `Chapter ${index + 1}: ${chapter.title}\n\n`;
            manuscriptContent += `${chapter.content}\n\n`;
        });
    }
    zip.file("manuscript.txt", manuscriptContent);

    // 2. Create Metadata File
    const metadata = {
        title: bookState.title,
        author: "Generated by Vibe Book Creator",
        blurb: bookState.blurb,
        keywords: bookState.kdpKeywords,
        categories: bookState.bookCategories
    };
    zip.file("metadata.json", JSON.stringify(metadata, null, 2));

    // 3. Generate the zip file
    const zipBlob = await zip.generateAsync({ type: "blob" });

    return zipBlob;
};
