
import { BookState } from '../types';
import JSZip from 'jszip';
import { Document, Packer, Paragraph, TextRun } from 'docx';
import { saveAs } from 'file-saver';

export const generateKDPPackage = async (bookState: BookState) => {
    const zip = new JSZip();

    let manuscriptContent = `Title: ${bookState.title || 'Untitled Book'}\n\n`;
    if (bookState.chapters) {
        bookState.chapters.forEach((chapter, index) => {
            manuscriptContent += `Chapter ${index + 1}: ${chapter.title}\n\n`;
            manuscriptContent += `${chapter.content}\n\n`;
        });
    }
    zip.file("manuscript.txt", manuscriptContent);

    const metadata = {
        title: bookState.title,
        author: "Generated by Vibe Book Creator",
        blurb: bookState.blurb,
        keywords: bookState.kdpKeywords,
        categories: bookState.bookCategories
    };
    zip.file("metadata.json", JSON.stringify(metadata, null, 2));

    const zipBlob = await zip.generateAsync({ type: "blob" });
    return zipBlob;
};

const generateDocumentContent = (bookState: BookState) => {
    const paragraphs: Paragraph[] = [];

    if (bookState.title) {
        paragraphs.push(new Paragraph({
            children: [new TextRun({ text: bookState.title, bold: true, size: 48 })],
            spacing: { after: 200 },
        }));
    }

    if (bookState.globalOutline) {
        paragraphs.push(new Paragraph({
            children: [new TextRun({ text: "Outline", bold: true, size: 36 })],
            spacing: { after: 200 },
        }));
        bookState.globalOutline.split('\n').forEach(line => {
            paragraphs.push(new Paragraph({ text: line }));
        });
    }

    if (bookState.chapters) {
        bookState.chapters.forEach((chapter, index) => {
            paragraphs.push(new Paragraph({
                children: [new TextRun({ text: `Chapter ${index + 1}: ${chapter.title}`, bold: true, size: 36 })],
                spacing: { after: 200 },
            }));
            chapter.content.split('\n').forEach(line => {
                paragraphs.push(new Paragraph({ text: line }));
            });
        });
    }
    return paragraphs;
};

export const exportAsDocx = (bookState: BookState, fileName: string) => {
    const doc = new Document({
        sections: [{
            properties: {},
            children: generateDocumentContent(bookState),
        }],
    });

    Packer.toBlob(doc).then(blob => {
        saveAs(blob, `${fileName}.docx`);
    });
};

export const exportAsMarkdown = (bookState: BookState, fileName: string) => {
    let markdownContent = `# ${bookState.title || 'Untitled Book'}\n\n`;
    if (bookState.globalOutline) {
        markdownContent += `## Outline\n\n${bookState.globalOutline}\n\n`;
    }
    if (bookState.chapters) {
        bookState.chapters.forEach((chapter, index) => {
            markdownContent += `## Chapter ${index + 1}: ${chapter.title}\n\n`;
            markdownContent += `${chapter.content}\n\n`;
        });
    }
    const blob = new Blob([markdownContent], { type: 'text/markdown;charset=utf-8' });
    saveAs(blob, `${fileName}.md`);
};

export const exportAsTxt = (bookState: BookState, fileName: string) => {
    let textContent = `Title: ${bookState.title || 'Untitled Book'}\n\n`;
    if (bookState.globalOutline) {
        textContent += `Outline\n\n${bookState.globalOutline}\n\n`;
    }
    if (bookState.chapters) {
        bookState.chapters.forEach((chapter, index) => {
            textContent += `Chapter ${index + 1}: ${chapter.title}\n\n`;
            textContent += `${chapter.content}\n\n`;
        });
    }
    const blob = new Blob([textContent], { type: 'text/plain;charset=utf-8' });
    saveAs(blob, `${fileName}.txt`);
};
